### ISSUE TITLE
[FR] Add an alternate "active" animation

### ISSUE THREAD

**Issue by ildar170975** [swingerman/lovelace-fluid-level-background-card#372]
**Is your feature request related to a problem? Please describe.**

Consider this config:
```
  - type: custom:fluid-level-background-card
    card:
      type: glance
      entities:
        - entity: person.ildar
    entity: input_number.test_level_1
    fill_entity: input_boolean.test_boolean
    level_color:
      - 244
      - 0
      - 204
```
Currently a "bubble" animation is shown if `fill_entity` = ON.
A "waves" animation is shown always.

I suggest a alternate variant:
-- if `fill_entity` = ON -> show "waves";
-- if `fill_entity` = OFF -> show a "still water".

A type of animation may be defined some new option like `bubbles_active`:
-- `true`:  the current behaviour (default);
-- `false`: do not show bubbles if `fill_entity` = ON, show only "waves"; if `fill_entity` = OFF - do not show "waves".

A reason behind this is that in some circumstances (people's age/eyes, a screen type, etc) these bubbles may be less visible.
Then a "wave" animation could be rather informative that "something is going on".

**Describe the solution you'd like**

see above.

**Describe alternatives you've considered**

See above.
 
**Additional context**
