### ISSUE TITLE
Fix some css imperfections

### ISSUE THREAD

**Issue by ildar170975** [swingerman/lovelace-fluid-level-background-card#373]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
0.1.4

**Last working release (if known):**

**Browser and Operating System:**
Chrome 122.0.6261.112 (Win10)

**Description of problem:**
Consider this config:
```
  - type: custom:fluid-level-background-card
    card:
      type: glance
      entities:
        - entity: sun.sun
    entity: input_number.test_level_1
    fill_entity: input_boolean.test_boolean
    level_color:
      - 244
      - 0
      - 204
```
![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/33eaa444-9a79-4698-8c3c-736f191eb630)

Scaled:

![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/d7308bad-9d11-42a0-8363-59ec61bc101d)

Here:
1. The inner card has a double border.
2. The background part overflows the inner card - it is clearly seen on bottom corners.
3. The background part has a box-shadow.

I managed to fix it by these styles:
```
      /* use only the inner card's border & box-shadow */
      div#container {
        border: none;
        box-shadow: none;
      }          
      /* use only the inner card's border & box-shadow */
      .type-custom-fluid-level-background-card {
        border: none;
        box-shadow: none;
      }
      /* use same shape as the inner card to avoid overflow */
      fluid-background {
        border-radius: var(--ha-card-border-radius,12px);
      }
```
After fix:

![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/042839a7-6f90-4e7f-bb08-11ebdca7bfba)

**Javascript errors shown in the web inspector (if applicable):**
none

**Additional information:**

**Comment by ildar170975** [comment]
@swingerman 
Thanks for the latest update!
But I still see a double border with a default theme:

![изображение](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/70faf352-111e-45ba-a788-a571c1cf59da)

```

    type: custom:fluid-level-background-card
    card:
      type: glance
      entities:
        - entity: sun.sun
          name: Beer level
    entity: input_number.test_level_1
    fill_entity: input_boolean.test_boolean
    level_color:
      - 242
      - 142
      - 28
```

Compared with my card-mod-tuned version:

![изображение](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/e3cda9ad-21f9-47e8-b801-3ec3efd001da)
