### ISSUE TITLE
[FR] Ability to define colors as "red", "#ff0000", "rgb/rgba(...)", "var(--some-var)"

### ISSUE THREAD

**Issue by ildar170975** [swingerman/lovelace-fluid-level-background-card#381]
**Is your feature request related to a problem? Please describe.**

Currently a color for `level_color` & `background_color` options is defined as a list:
```
level_color: [255,0,0]
```
or
```
level_color:
  - 255
  - 0
  - 0
```
We cannot use these variants:
```
level_color: red
level_color: 'red'
level_color: '#ff0000'
level_color: var(--red-color)
level_color: 'var(--red-color)'
level_color: rgb(242,142,28) # or rgba()
level_color: 'rgb(242,142,28)' # or rgba()
```
These variants are commonly used in many other cards (mainly custom cards since stock cards do not support defining colors explicitly, only by themes or card-mod).

Possible use-cases with the proposed approach:
1. User may define a global CSS theme variable to represent a "color of water" & then use it for graphs / progressbar-like cards (like [bar-card](https://github.com/custom-cards/bar-card)) and this `fluid-level-background-card`. Assume this variable is called `--water-color`, then a code will be:
```
level_color: var(--water-color)
```
2. A similar case with using yaml-anchors:
```
color: &ref_water_color rgb(xxx,xxx,xxx) # for some another card
...
level_color: *ref_water_color
```

This proposal could be NOT a BREAKING change if the currently used "list" variant stays supported along with the new proposed ways.

**Describe the solution you'd like**
Please see above.

**Describe alternatives you've considered**

**Additional context**

**Comment by swingerman** [comment]
please check [v0.1.6-beta.2](https://github.com/swingerman/lovelace-fluid-level-background-card/releases/tag/v0.1.6-beta.2)

**Comment by ildar170975** [comment]
You are brilliant! Thanks, will start testing.

**Comment by ildar170975** [comment]
What I noticed while testing:
```
type: vertical-stack
cards:
  - type: custom:fluid-level-background-card
    card:
      type: glance
      entities:
        - entity: sun.sun
          name: Beer level
    entity: input_number.test_level_1
    fill_entity: input_boolean.test_boolean
    level_color: rgba(255,0,0,0.1)

  - type: custom:fluid-level-background-card
    card:
      type: glance
      entities:
        - entity: sun.sun
          name: Beer level
    entity: input_number.test_level_1
    fill_entity: input_boolean.test_boolean
    level_color: '#ff0000'

  - type: custom:fluid-level-background-card
    card:
      type: glance
      entities:
        - entity: sun.sun
          name: Beer level
    entity: input_number.test_level_1
    fill_entity: input_boolean.test_boolean
    level_color: #ff0000
```
![изображение](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/1b99d1f0-bc26-4e15-9ba3-83a4acc02007)

1. In `rgba` case the alpha channel not set.
2. If hex value is not defined in quotes - then probably it is considered as a comment. After save & reopening I see this:
```
level_color: null
```
And color is blue. But in "const.ts" it is still `[0, 128, 0]`. Is it a bug or by a design?
Imho a blue color is a good choice for a default value - but some users may think that this is a "breaking change" )).
