### ISSUE TITLE
Its not updating the sensor value

### ISSUE THREAD

**Issue by hjkss** [swingerman/lovelace-fluid-level-background-card#424]
Have to refresh the page to get the updated sensor value

**Comment by ildar170975** [comment]
Do not confirm.
![ffff](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/9c08ed7a-0833-41d6-b29e-9868940e24fa)
```
      - type: entities
        entities:
          - input_boolean.test_boolean
          - input_number.test_level_1

      - type: custom:fluid-level-background-card
        card:
          type: glance
          entities:
            - entity: sun.sun
              name: Beer level
        entity: input_number.test_level_1
        fill_entity: input_boolean.test_boolean
        level_color: lightblue
```
