### ISSUE TITLE
[feat] - alpha channel

### ISSUE THREAD

**Issue by Ftown14** [swingerman/lovelace-fluid-level-background-card#429]
**Is your feature request related to a problem? Please describe.**

It is not related to an issue

**Describe the solution you'd like**
First off, thank you for this card and all the effort you have put into making/upkeeping it.

Would be is be possible to add the alpha channel? I ask because then instead of just using the traditional bar-card or similar, it would allow for it to be used as an overlay on images of bottles, containers, etc. 

**Describe alternatives you've considered**

This should be able to be done by editing the image to make the fluid area a transparent layer, but with the alpha channel you could leave the image as is and maintain the details/design.

**Additional context**

If these isn't feasible, then I understand. Either way I love this card and surprised you are the only one to have created something like this. Thank you.

**Comment by ildar170975** [comment]
A possible workaround: place this card UNDER another card and change an opacity of that topmost card by card-mod.

**Comment by swingerman** [comment]
Please check [v0.1.8](https://github.com/swingerman/lovelace-fluid-level-background-card/releases/tag/v0.1.8)

**Comment by ildar170975** [comment]
Thanks a lot !!!!

**Comment by ildar170975** [comment]
Noticed a small glitch:
1. After F5 (reload a browser's page) an alpha channel may NOT be applied.
2. Then it is applied after a few seconds.
 
![Untitled Project](https://github.com/user-attachments/assets/eb9e34bc-a485-43c5-83c7-18e7aeca3afd)
```
type: custom:fluid-level-background-card
card:
  type: glance
  entities:
    - entity: sun.sun
      name: Beer level
entity: input_number.test_level_1
fill_entity: input_boolean.test_boolean
level_color:
  - 242
  - 142
  - 28
  - 0.1
```
HA 2024.8, Chrome 127.0.6533.89
