### ISSUE TITLE
[bug] - color alpha not applied in some cases

### ISSUE THREAD

**Issue by swingerman** [swingerman/lovelace-fluid-level-background-card#437]
1. After F5 (reload a browser's page) an alpha channel may NOT be applied.
2. Then it is applied after a few seconds.
 
![Untitled Project](https://github.com/user-attachments/assets/eb9e34bc-a485-43c5-83c7-18e7aeca3afd)
```
type: custom:fluid-level-background-card
card:
  type: glance
  entities:
    - entity: sun.sun
      name: Beer level
entity: input_number.test_level_1
fill_entity: input_boolean.test_boolean
level_color:
  - 242
  - 142
  - 28
  - 0.1
```
HA 2024.8, Chrome 127.0.6533.89

_Originally posted by @ildar170975 in https://github.com/swingerman/lovelace-fluid-level-background-card/issues/429#issuecomment-2274909160_
