### ISSUE TITLE
Unable to interact with card with fluid wrapper

### ISSUE THREAD

**Issue by fishter** [swingerman/lovelace-fluid-level-background-card#492]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
0.1.8.3

**Last working release (if known):**
Unknown - this is my first install

**Browser and Operating System:**
Android 14 with:
- Chrome 131.0.6778.104
- Home assistant companion app 2024.10.3-full
- both show the same issue

It works in chrome on windows 11 (131.0.6778.86 & 109)

**Description of problem:**
Here's the yaml for my card. 
```
type: custom:fluid-level-background-card
card:
  type: humidifier
  entity: humidifier.dehumidifier
  show_current_as_primary: true
  features:
    - type: humidifier-toggle
entity: sensor.dehumidifier_water_level
severity:
  - color:
      - 0
      - 255
      - 0
    value: 25
  - color:
      - 255
      - 187
      - 0
    value: 50
  - color: "#FF0000"
    value: 75
```
When I tap on the humidifier +/- to nudge the setpoint up or down it doesn't respond.
When I tap the off button the button goes grey (like it's been pressed) but nothing occurs on my device.
If I remove the fluid background it works normally.

**Javascript errors shown in the web inspector (if applicable):**

Sorry, I don't know how to access this on mobile.

**Additional information:**

**Comment by ildar170975** [comment]
Imho this is not about humidifier.
Consider 2 cards:
```
type: entities
entities:
  - input_number.test_number
```
```
type: custom:fluid-level-background-card
card:
  type: entities
  entities:
    - input_number.test_number
entity: input_number.test_level_1
```
![ff](https://github.com/user-attachments/assets/5182f750-a307-404d-a69f-45a9e059b77c)
An inner card is like not getting updates from HASS.
