### ISSUE TITLE
Round corners?

### ISSUE THREAD

**Issue by Psytoshgen** [swingerman/lovelace-fluid-level-background-card#50]
Hi! Can you add round corners support?
![A0375354-1E31-4BE2-BA5E-39D0924B3815](https://user-images.githubusercontent.com/94195788/158028878-7224f6b1-9f2c-445a-93f2-db75ca968984.png)

Used “outline” theme for cards and dark iOS for background

**Comment by Dejv311** [comment]
Hi, I am still getting the corners outside the boundary box. Using Soft UI theme for HA.

```
type: custom:fluid-level-background-card
card:
  show_name: true
  show_icon: true
  type: button
  tap_action:
    action: toggle
  entity: switch.#####
  name: ggfsgsfdg
entity: sensor.#####
```

![image](https://user-images.githubusercontent.com/46622252/169882310-3b11460d-7c1c-4fa7-8b84-fd66f228280b.png)
