### ISSUE TITLE
Sensor not updated (#2)

### ISSUE THREAD

**Issue by Protoncek** [swingerman/lovelace-fluid-level-background-card#522]
**Checklist:**

- [ x] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Browser and Operating System:** Windows 11

**Description of problem:**
I have a scale, made with esphome which shows current weight of water bowl for my dogs (so i monitor when it's empty). I use "custom:button-card"  as my main card.
I inserted label on my card, which should show a text if certain automation (warning speech when bowl is empty) is on or off. If i hold on card automation is toggled ok, but information on card doesn't "see that" until i hit F5 on my browser. The funny thing is that basic sensor (bowl weight) is normally updated.
Am i doing something wrong in card ? 
my whole card:
```
type: custom:fluid-level-background-card
entity: sensor.pasja_vaga_neto
full_value: "5"
card:
  type: custom:button-card
  name: |
    [[[
    if (states['sensor.pasja_vaga_neto'].state > 0 )
      return "Pasja voda"
    else
      if  (states['sensor.pasja_vaga_teza_v_kg'].state != 'unavailable')
        return "čiščenje..."
      else
        return "Pasja voda"
    ]]]
  tap_action:
    action: call-service
    service: button.press
    service_data:
      entity_id: button.pasja_vaga_tara_rocni_reset
    confirmation:
      text: Ali resetiram TARO? POZOR!!! Posoda mora biti odstranjena!!!
  hold_action:
    action: call-service
    service: automation.toggle
    service_data:
      entity_id: automation.pasja_voda_prazna_nova
  show_label: true
  label: |
    [[[
    if (states['automation.pasja_voda_prazna_nova'].state == 'off')
      return "OPOZORILO IZKLJUČENO!"
    else
      return ""
    ]]]
  styles:
    card:
      - height: 190px
      - text-shadow: 3px 3px 3px black
      - font-size: 30px
      - font: 65px/70px'Ink Free'
      - font-weight: bold
      - border-radius: 20px
      - box-shadow: >
          [[[ if (states['sensor.pasja_vaga_neto'].state<2.0 ||
          states['sensor.pasja_vaga_neto'].state =='unavailable' ||
          states['automation.pasja_voda_prazna_nova'].state == 'off' )
            return "inset 0 0 10px 5px  red"
          else
            return "inset 0 0 10px 5px  white"
          ]]]
      - animation: >
          [[[

          if (states['sensor.pasja_vaga_neto'].state<2 ||
          states['sensor.pasja_vaga_neto'].state =='unavailable')
            return "blink 1s ease infinite"

          ]]]
    label:
      - font-size: 15px
  show_state: true
  state_display: |
    [[[
    if (states['sensor.pasja_vaga_neto'].state > 0 )
      return states['sensor.pasja_vaga_neto'].state + " L"
    else
      if  (states['sensor.pasja_vaga_teza_v_kg'].state != 'unavailable')
        return "TARA: "+states['sensor.pasja_vaga_teza_v_kg'].state + " kg"
      else
        return "ni na voljo!"
    ]]]
  show_icon: false
  entity: sensor.pasja_vaga_neto
  severity:
    - value: 20
      color: red
severity:
  - color: "#FF0000"
    value: 15
  - color:
      - 242
      - 167
      - 38
    value: 20
  - color:
      - 24
      - 175
      - 205
    value: 40
level_color:
  - 81
  - 163
  - 25
fill_entity: input_boolean.kiosk_kuhinja
card_mod:
  style: |
    ha-card {
      --ha-card-header-font-size: 12px;
      text-align: center;
    }
```

**Comment by ildar170975** [comment]
Strongly suggest you to SIMPLIFY your test code.
The `fluid-level-background-card` has 20% of a whole code...
This repo is not for button-card.

**Comment by Protoncek** [comment]
Yes, i did complicate a bit, agreed. But the problem is not custom button card, because same card works perfectly when it's placed as standalone card, only inside fluid card doesn't.

**Comment by ildar170975** [comment]
Well, this code with templates work OK as well:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_boolean.test_boolean
      - input_number.test_level_1
  - type: custom:fluid-level-background-card
    entity: input_number.test_level_1
    card:
      type: custom:button-card
      entity: input_boolean.test_boolean
      name: |-
        [[[
          return "state=" + entity.state + ', level=' + states['input_number.test_level_1'].state;
        ]]]
    fill_entity: input_boolean.test_boolean
```

**Comment by Protoncek** [comment]
Yes, thanks, i changed my card into vertical stack, as you suggested, it seems it's the only solution.  It's not exactly as i planned, but it'll do.

**Comment by ildar170975** [comment]
@Protoncek 
> into vertical stack, as you suggested

This is not what I suggested.
I suggested to simplify a code - and then increase a complexity step-by-step - to find out a culprit.

**Comment by Protoncek** [comment]
I did that - i deleted pretty much everything and made it very simple:
```
type: custom:fluid-level-background-card
entity: sensor.pasja_vaga_neto
card:
  type: custom:button-card
  entity: sensor.pasja_vaga_neto
  show_icon: false
  show_label: true
  show_state: true
  name: |
    [[[
    if (states['input_boolean.test'].state == 'off')
      return "boolean OFF"
    else
      return "boolean ON"
    ]]]
  label: ""
```

But still doesn't work when i toggle input boolean until i hit F5 - then it shows new state.

**Comment by ildar170975** [comment]
I see.
Here is a (hopefully) reproducible example:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_number.test_level_1
      - input_boolean.test_boolean
  - type: custom:fluid-level-background-card
    entity: input_number.test_level_1
    #fill_entity: input_boolean.test_boolean
    card:
      type: custom:button-card
      entity: input_boolean.test_boolean
```
![Image](https://github.com/user-attachments/assets/2ad44fe2-4625-45fe-88c4-9ea7e7f61619)

How it works:
1. Toggle`'input_boolean.test_boolean` entity.
2. The inner button-card is not updated.
3. Change `input_number.test_level_1` entity.
4. The `fluid-level-background-card` updates itself - and also updates the inner card.
5. Uncomment the `fill_entity: input_boolean.test_boolean`.
6. Now the inner card is updated properly.

@swingerman Please have a look.
