### ISSUE TITLE
level background color display error.

### ISSUE THREAD

**Issue by Ainndy** [swingerman/lovelace-fluid-level-background-card#553]
https://github.com/user-attachments/assets/fb379721-bfd2-470a-85df-1184cfff0683

```
type: custom:fluid-level-background-card
card:
  show_name: true
  show_icon: true
  type: button
  entity: sun.sun
  show_state: true
level_color:
  - 0
  - 66
  - 169
entity: input_number.test_level_1

```
