### ISSUE TITLE
The `full_value` attribute does not recognize entity value if < 1.0

### ISSUE THREAD

**Issue by CurryPlayer** [swingerman/lovelace-fluid-level-background-card#567]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Version 0.1.8.5

**Last working release (if known):**

**Browser and Operating System:**
- Google Chrome (137.0.7151.104 (Offical Build) (64-Bit))
- HAOS 15.2, Core: 2025.5.3, Frontend: 20250516.0

**Description of problem:**
I want to display my daily energy consumption in kilowatt hours (kWh) in liquid form :D. The maximum `full_value` is set to _1.8_ kWh. The entity which provides this value is a _'Combine the state of several sensors'_ helper, consists of multiple _'Utility Meter'_ helpers, which have their units all set to _kWh_.

If the entity `sensor.all_devices_today_s_energy_consumption` has a value < 1.0, the fluid is stuck at the bottom and would probably show 0%. But as soon as the value of this entity is set to >= 1.0, the fluid works as it should up until the set `full_value` of _1.8_

Here is my code:
```yaml
type: custom:fluid-level-background-card
card:
  type: tile
  entity: sensor.all_devices_today_s_energy_consumption
  features_position: bottom
  vertical: true
  hide_state: false
  show_entity_picture: false
  icon: mdi:lightning-bolt
  name: Today's Energy Consumption
full_value: 1.8
entity: sensor.all_devices_today_s_energy_consumption
```

And here are two pictures:
- A value < _1.0_:
![Image](https://github.com/user-attachments/assets/501f2427-e9bc-4b72-a19f-84aac1b8c0b7)
- A value >= _1.0_:
![Image](https://github.com/user-attachments/assets/903c8e16-18d9-432e-8b28-e8e4dfc8a181)

**Javascript errors shown in the web inspector (if applicable):**
No errors are shown in browser console

**Additional information:**
